server:
  port: 8090
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/ECOMMERCE?stringtype=unspecified
    username: postgres
    password: admin123
    driverClassName: org.postgresql.Driver
---
spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
      group-id: group-id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    admin:
      properties:
        bootstrap.servers: localhost:9092,localhost:9093,localhost:9094
        
